// Mirrors catalog/phase1/catalog.json → lookups.units (generated by catalog/tools/build_phase1_catalog.py).
// Clients load the live registry from GET /api/v1/units; this copy serves offline use and tests.

export type Dimension = 'speed' | 'mass' | 'length' | 'duration' | 'energy' | 'volume' | 'pace';
export type UnitSystem = 'METRIC' | 'IMPERIAL' | 'BOTH';

export interface UnitDefinition {
  code: string;
  label: string;
  dimension: Dimension | null;
  toBase: number | null;
  system: UnitSystem;
  counterpart: string | null;
  decimals: number;
  step: number | null;
}

const u = (
  code: string,
  label: string,
  dimension: Dimension | null = null,
  toBase: number | null = null,
  system: UnitSystem = 'BOTH',
  counterpart: string | null = null,
  decimals = 1,
  step: number | null = null,
): UnitDefinition => ({ code, label, dimension, toBase, system, counterpart, decimals, step });

export const DEFAULT_UNITS: readonly UnitDefinition[] = [
  u('km/h', 'kilometres per hour', 'speed', 1 / 3.6, 'METRIC', 'mph', 1, 0.1),
  u('mph', 'miles per hour', 'speed', 0.44704, 'IMPERIAL', 'km/h', 1, 0.1),
  u('m/s', 'metres per second', 'speed', 1, 'METRIC', 'ft/s', 2, 0.1),
  u('ft/s', 'feet per second', 'speed', 0.3048, 'IMPERIAL', 'm/s', 1, 0.1),
  u('kg', 'kilograms', 'mass', 1, 'METRIC', 'lb', 2, 0.25),
  u('g', 'grams', 'mass', 0.001, 'METRIC', 'oz', 0, 1),
  u('lb', 'pounds', 'mass', 0.45359237, 'IMPERIAL', 'kg', 1, 0.5),
  u('oz', 'ounces', 'mass', 0.028349523125, 'IMPERIAL', 'g', 1, 0.5),
  u('st', 'stone', 'mass', 6.35029318, 'IMPERIAL', 'kg', 2, 0.1),
  u('km', 'kilometres', 'length', 1000, 'METRIC', 'mi', 2, 0.01),
  u('m', 'metres', 'length', 1, 'METRIC', 'yd', 1, 0.1),
  u('cm', 'centimetres', 'length', 0.01, 'METRIC', 'in', 1, 0.5),
  u('mm', 'millimetres', 'length', 0.001, 'METRIC', 'in', 0, 1),
  u('mi', 'miles', 'length', 1609.344, 'IMPERIAL', 'km', 2, 0.01),
  u('yd', 'yards', 'length', 0.9144, 'IMPERIAL', 'm', 1, 0.1),
  u('ft', 'feet', 'length', 0.3048, 'IMPERIAL', 'm', 1, 0.1),
  u('in', 'inches', 'length', 0.0254, 'IMPERIAL', 'cm', 1, 0.25),
  u('ms', 'milliseconds', 'duration', 0.001, 'BOTH', null, 0, 1),
  u('s', 'seconds', 'duration', 1, 'BOTH', null, 2, 0.01),
  u('min', 'minutes', 'duration', 60, 'BOTH', null, 1, 1),
  u('h', 'hours', 'duration', 3600, 'BOTH', null, 2, 0.25),
  u('kcal', 'kilocalories', 'energy', 1, 'BOTH', null, 0, 1),
  u('kJ', 'kilojoules', 'energy', 1 / 4.184, 'METRIC', null, 0, 1),
  u('ml', 'millilitres', 'volume', 0.001, 'METRIC', 'fl oz', 0, 1),
  u('l', 'litres', 'volume', 1, 'METRIC', 'qt', 2, 0.05),
  u('fl oz', 'US fluid ounces', 'volume', 0.0295735295625, 'IMPERIAL', 'ml', 1, 0.5),
  u('qt', 'US quarts', 'volume', 0.946352946, 'IMPERIAL', 'l', 2, 0.05),
  u('s/m', 'seconds per metre (raw pace)', 'pace', 1, 'BOTH', null, 3),
  u('min/km', 'minutes per kilometre', 'pace', 0.06, 'METRIC', 'min/mi', 2),
  u('min/mi', 'minutes per mile', 'pace', 60 / 1609.344, 'IMPERIAL', 'min/km', 2),
  u('reps', 'repetitions'),
  u('bpm', 'beats per minute'),
  u('rpm', 'revolutions per minute'),
  u('spm', 'steps per minute'),
  u('%', 'percent'),
  u('AU', 'arbitrary units'),
];
